### ISSUE TITLE
Authentication is broken. (Twitter Version 4.1.3)

### ISSUE THREAD

**Issue by thecinnsystem** [Preloading/TwitterAPIBridge#23]
Sometime between today and 12/26 authentication broke for me. Trying to login simply gets me 

"14:42:27 | 404 |            0s | 10.0.0.65 | POST | /oauth/access_token | Cannot POST /oauth/access_token"

It previously WAS working on commit 44b9caa. On the iOS side it simply says "Could not authenticate you. (not found)"

**Comment by thecinnsystem** [comment]
It DOES work if I'm already signed in, but I can't sign in.

**Comment by Preloading** [comment]
My bad, it looks like I accediently did keyboard spam on the auth request

Fixed in 41c58e6
